### ISSUE TITLE
Artifacts not available in workflow

### ISSUE THREAD

**Issue by Bo-Brown-Dev** [movestore/python-sdk#6]
My app is intended to create 3 artifacts: A Geopackage, a CSV, and an html map. 

I ran the app in a workflow on a dataset that I have tested and checked for Artifacts (the app generates Artifacts in output directory when being run locally with this dataset as a sample file). From the workflow I see only App-Output.pickle.
I have:
checked that I am saving them to the right location using the moveapps_io.py method
Checked that my Appspec.json is set with "CreatesArtifacts": true
I have checked the logs and it looks like each function in the program is running properly.
The output of the file appears to be correct as well.

I'm wondering if I'm missing a setting somewhere or if there is anything else that I should try?

**Comment by andreakoelzsch** [comment]
HI Bo, I canno think of anything else, maybe @cleemansen can help here? thanks!

**Comment by andreakoelzsch** [comment]
@cleemansen It is this Python App: https://github.com/Bo-Brown-Dev/Road-Crossings (Road Crossings on MoveApps)

**Comment by cleemansen** [comment]
closed w/ https://github.com/Bo-Brown-Dev/Road-Crossings/issues/2
